FROM scratch
ADD go-dl-extract-Linux-x86_64 /bin/sh

RUN http://192.168.59.3:8989/rootfs.tar
#RUN -v http://192.168.59.3:8989/rootfs.tar
#RUN -v http://192.168.59.3:8989/debian/rootfs.tar

RUN echo "Hello World"
